version: "3.9"

services:
  # TODO: App container will be here

  postgres-kinitializr:
    image: postgres:14.4-alpine
    container_name: postgres-kinitializr
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=kinitializr
      - POSTGRES_USER=kinitializr
      - POSTGRES_PASSWORD=kinitializr
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U user -d databaseName' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  postgres_data: